name: Drizzle Push
on:
  push:
    branches:
      - main
      - dev
      - dev/*

  workflow_dispatch:

jobs:
  database-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Push any changes
        run: bun run push
        env:
          ADMIN_DATABASE_URL: ${{ secrets.ADMIN_DATABASE_URL }}
